---
name: generate-projects

on:
  workflow_dispatch:
  schedule:
    - cron: "3 3 * * 3"

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2

      - name: Generate _tabs/projects.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install --save-dev --save-exact prettier
          scripts/generate-projects.sh _tabs/projects.md

      - name: Restore lychee cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a # v1.9.3
        with:
          args: "_tabs/projects.md"
          fail: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with:
          add-paths: _tabs/projects.md
          branch: generate-projects
          commit-message: "docs(projects): update _tabs/projects.md"
          delete-branch: true
          labels: generate-projects
          title: "docs(projects): update _tabs/projects.md"
